cc_library(
    name = "frame_decapsulate",
    srcs = ["FrameDecapsulate.cpp"],
    hdrs = ["FrameDecapsulate.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "@opencv//:opencv",
    ],
)

cc_library(
    name = "frame",
    srcs = ["Frame.cpp"],
    hdrs = ["Frame.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "@opencv//:opencv",
    ],
)
