cc_test(
	name = "encapsulation_unit_tests",
	srcs = ["Encapsulation.unit.cpp"],
	deps = [
		"//src/common/dataManager/encapsulation:Decapsulator",
		"//src/common/dataManager/encapsulation:Encapsulator",
		"@googletest//:gtest_main",
	],
	linkstatic = 1,
)
