load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "new_git_repository")

# CMake

# Rule repository
http_archive(
    name = "rules_foreign_cc",
    sha256 = "d54742ffbdc6924f222d2179f0e10e911c5c659c4ae74158e9fe827aad862ac6",
    strip_prefix = "rules_foreign_cc-0.2.0",
    url = "https://github.com/bazelbuild/rules_foreign_cc/archive/0.2.0.tar.gz",
)

load("@rules_foreign_cc//foreign_cc:repositories.bzl", "rules_foreign_cc_dependencies")

rules_foreign_cc_dependencies()

# [
#    "//:built_cmake_toolchain",
#]

# Repository

git_repository(
    name = "googletest",
    remote = "https://github.com/google/googletest",
    commit = "2fe3bd994b3189899d93f1d5a881e725e046fdc2",
    shallow_since = "1535728917 -0400"
)

git_repository(
    name = "benchmark",
    remote = "https://github.com/google/benchmark.git",
    commit = "1d41de84633bf40ddf0ad50165d77200e3d8b5fd",
    shallow_since = "1555517332 +0100",
)

http_archive(
    name = "com_google_protobuf",
    sha256 = "9510dd2afc29e7245e9e884336f848c8a6600a14ae726adb6befdb4f786f0be2",
    strip_prefix = "protobuf-3.6.1.3",
    urls = ["https://github.com/protocolbuffers/protobuf/archive/v3.6.1.3.zip"],
)

http_archive(
    name = "opencv",
    sha256 = "2c75b129da2e2c8728d168b7bf14ceca2da0ebe938557b109bae6742855ede13",
    build_file = "opencv.BUILD",
    strip_prefix = "opencv-4.1.0",
    urls = ["https://github.com/opencv/opencv/archive/4.1.0.zip"],
)

new_git_repository(
    name = "moodycamel_concurrentqueue",
    remote = "https://github.com/cameron314/concurrentqueue",
    commit = "dea078cf5b6e742cd67a0d725e36f872feca4de4",
    build_file = "concurrentqueue.BUILD",
    shallow_since = "1547235167 -0500",
)

new_git_repository(
    name = "moodycamel_readerwriterqueue",
    remote = "https://github.com/cameron314/readerwriterqueue",
    commit = "2ae710de996a1d02bbc7696b2cdff2c6078e76f8",
    build_file = "readerwriterqueue.BUILD",
    shallow_since = "1549905904 -0500",
)

http_archive(
    name = "com_google_absl",
    urls = ["https://github.com/abseil/abseil-cpp/archive/master.zip"],
    strip_prefix = "abseil-cpp-master",
)

http_archive(
    name = "muduo",
    strip_prefix = "muduo-master",
    urls = ["https://github.com/chenshuo/muduo/archive/master.zip"],
)

# Docker

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Download the rules_docker repository at release v0.7.0
http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "59d5b42ac315e7eadffa944e86e90c2990110a1c8075f1cd145f487e999d22b3",
    strip_prefix = "rules_docker-0.17.0",
    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.17.0/rules_docker-v0.17.0.tar.gz"],
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)
container_repositories()

load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")

container_deps()

load(
    "@io_bazel_rules_docker//container:container.bzl",
    "container_pull",
)

container_pull(
    name = "official_ubuntu",
    registry = "index.docker.io",
    repository = "library/ubuntu",
    tag = "disco",
)

# NDK rule

# Require that ANDROID_HOME must be set
android_sdk_repository(
    name = "androidsdk", # Required. Name *must* be "androidsdk".
    api_level = 25,
)

# Require that ANDROID_NDK_HOME must be set
android_ndk_repository(
    name = "androidndk", # Required. Name *must* be "androidndk".
)

#http_archive(
#    name = "build_stack_rules_proto",
#    urls = ["https://github.com/stackb/rules_proto/archive/91cbae9bd71a9c51406014b8b3c931652fb6e660.tar.gz"],
#    sha256 = "5474d1b83e24ec1a6db371033a27ff7aff412f2b23abba86fedd902330b61ee6",
#    strip_prefix = "rules_proto-91cbae9bd71a9c51406014b8b3c931652fb6e660",
#)

#load("@build_stack_rules_proto//cpp:deps.bzl", "cpp_proto_compile")

#cpp_proto_compile()

#http_archive(
#    name = "boost",
#    build_file = "boost.BUILD",
#    sha256 = "430ae8354789de4fd19ee52f3b1f739e1fba576f0aded0897c3c2bc00fb38778",
#    strip_prefix = "boost_1_70_0",
#    url = "https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.bz2",
#)
